const charactersDemonSlayer = [
  {
    id: 0,
    name: 'Tanjiro Kamado',
    skills: ['Respiração da Água', 'Respiração do Sol'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_S8i6UWxwBp7I.jpg.jpeg',
    description: 'Filho mais velho de uma extensa família massacrada por um oni, Tanjiro Kamado é o protagonista da história. Para encontrar uma cura para sua irmã, ele escolheu trilhar o caminho dos Caçadores de Onis. Ele treinou por anos junto do mestre Sakonji Urokodaki antes de participar da seleção para entrar para a Corporação.',
  },
  {
    id: 1,
    name: 'Nezuko Kamado',
    skills: ['Força Bruta', 'Super Regeneração', 'Kekeijutsu'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_aQLskf53TUVR.jpg.jpeg',
    description: 'Era apenas um pouco mais nova que Tanjiro quando sua família foi morta pelo misterioso Muzan Kibutsuji, que a transformou em um demônio. A força bruta de Nezuko Kamado foi amplificada com a transformação, que também trouxe um surto de agilidade, resistência e uma sede insaciável por sangue humano.',
  },
  {
    id: 2,
    name: 'Zenitsu Agatsuma',
    skills: ['Respiração do Relâmpago'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_Zf3abSW6EJ5v.jpg.jpeg',
    description: 'Zenitsu Agatsuma é um Caçador de Demônios que usa a Respiração do Trovão. Treinado pelo ex-hashira Jigoro Kuwajima, nunca confiou nas próprias habilidades, mas seu mestre viu seu potencial. Naturalmente covarde e mulherengo, está sempre fugindo de batalhas, buscando o caminho mais fácil e dando em cima de garotas.',
  },
  {
    id: 3,
    name: 'Inosuke Hashibira',
    skills: ['Respiração da Besta'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_WrM125jhuKfD.jpg.jpeg',
    description: 'Inosuke Hashibira é um Caçador de Recompensas usuário da Respiração da Besta. Ele cresceu isolado em uma montanha, entre os javalis selvagens e sozinho criou a sua própria Técnica de Respiração, derivada da Respiração do Vento. Por esse motivo, não sabe interagir socialmente e está sempre chamando todo mundo para brigar.',
  },
  {
    id: 4,
    name: 'Kanao Tsuyuri',
    skills: ['Respiração das Flores'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_Ov3ZGQ5s07CV.jpg.jpeg',
    description: 'Kanao Tsuyuri é a Tsuguko, a futura Hashira da Respiração das Flores. Ela teve um passado bem abusivo e por isso reprime ao máximo suas emoções. Também não confia em suas próprias escolhas e usa uma moeda quando precisa tomar uma decisão. Acaba se aproximando de Tanjiro com o passar do tempo.',
  },
  {
    id: 5,
    name: 'Sakonji Urokodaki',
    skills: ['Respiração da Água'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_mF9DE5LjCeqy.jpg.jpeg',
    description: 'Sakonji Urokodaki é o ex-hashira da Respiração da Água. Ele é um homem de meia-idade, de coração mole, que sempre esconde o rosto por debaixo de uma máscara de Tengu. Ensina para crianças tudo que pode sobre a Respiração na esperança que sobrevivam ao Exame de Caçador de Onis. Entre seus alunos mais notáveis, temos Tanjiro e Giyu.',
  },
  {
    id: 6,
    name: 'Muzan Kibutsuji',
    skills: ['Kekeijutsu Supremo'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_oIHDvV7LCixk.jpg.jpeg',
    description: 'Muzan Kibutsuji é o grande vilão de Kimetsu no Yaiba. Foi ele quem assassinou toda a família de Tanjiro e transformou Nezuko em demônio. Ele é, inclusive, o Rei dos Demônios, o primeiro deles. Seu sangue tem o poder de transformar humanos em demônios. Ardiloso, mente, engana e se esconde entre os humanos. É o líder dos Doze Kizuki.',
  },
  {
    id: 7,
    name: 'Shinobu Kocho',
    skills: ['Respiração dos Insetos'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_1oRCXPzUY76y.jpg.jpeg',
    description: 'Shinobu Kocho é o pilar da Respiração dos Insetos. Sua aparência meiga é compatível com o seu jeito de agir: manso, fofo e delicado. Mas no fundo é tudo falsidade, como uma venenosa borboleta monarca. Ela oferece torturar onis para que paguem por seus pecados, do jeito mais gentil possível. Suas técnicas perfuram, ao invés de cortar, e envenenam os demônios com essência de Glicíneas.',
  },
  {
    id: 8,
    name: 'Giyu Tomioka',
    skills: ['Respiração da Água'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_5B4f60kjCI7y.jpg.jpeg',
    description: 'Giyu Tomioka é o Pilar da Respiração da Água, pupilo de Urokodaki. Ele tem um jeitão rústico, de poucos amigos, mas é uma pessoa simpática e extremamente justa. É tão poderoso que conseguiu superar seu mestre, criando novas formas da Respiração da Água. Consegue derrotar um onis mantendo a mais pura calma, sem parecer se mover.',
  },
  {
    id: 9,
    name: 'Mitsuri Kanroji',
    skills: ['Respiração do Amor'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_R2kqlV43rzOx.jpg.jpeg',
    description: 'Mitsuki Kanroji é a Hashira da Respiração do Amor. Ela consegue ver o melhor em cada um e se apaixona por todos. Demonstrações de amor a deixam toda derretidinha. O jeito mais fácil de defini-la é com a canção “Amor de Que”, da Pabllo Vittar. Seus ataques são como um chicote.',
  },
  {
    id: 10,
    name: 'Kyojuro Rengoku',
    skills: ['Respiração das Chamas'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_6mTOnFc5tyQ9.jpg.jpeg',
    description: 'Kyojuro Rengoku é a Hashira de Respiração das Chamas. Ele é empolgado em tudo o que faz, como um labrador humano. Tudo que faz é com uma imensa animação e defende a crença de que os mais fortes tem o dever de proteger os mais fracos. Ele tem um papel crucial no filme Demon Slayer: Mugen Train.',
  },
  {
    id: 11,
    name: 'Tengen Uzui',
    skills: ['Respiração do Som'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_0XRf5BCN9p7z.jpg.jpeg',
    description: 'Tengen Uzui é o Hashira da Respiração do Som. Ele é uma pessoa de aparências, que tenta fazer tudo do jeito mais extravagante possível. Mas essa sua preocupação em impressionar é uma resposta a sua baixa auto-estima. Tem três esposas e ataca com duas espadas. Em combate, usa o som dos inimigos para derrotá-los.',
  },
  {
    id: 12,
    name: 'Gyomei Himejima',
    skills: ['Respiração da Pedra'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_Nj_Cq6hxXkgm.jpg.jpeg',
    description: 'Gyomei Himejima é o Hashira de Respiração da Pedra. Ele segue os ensinamentos budistas e está sempre chorando pela humanidade. Fala com paciência, compaixão e pena por todos, apesar de julgá-los um pouco. Foi o mentor de Shinazugawa e, em combate, luta usando um machado preso a uma maça por uma corrente.',
  },
  {
    id: 13,
    name: 'Obanai Iguro',
    skills: ['Respiração da Serpente'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_0Zkwt3Qzdn4m.jpg.jpeg',
    description: 'Obanai Iguro é o Hashira de Respiração da Serpente. Ele é impetuoso com aqueles que desviam da conduta por zelar pelo futuro da Corporação acima de tudo, até mesmo de seus companheiros. Está sempre colocando os demais para baixo e ataca com uma espada ondulada usando sua Respiração única.',
  },
  {
    id: 14,
    name: 'Muichiro Tokito',
    skills: ['Respiração da Névoa'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_WMSaCv09cTjm.jpg.jpeg',
    description: 'Muichiro Tokito é o Hashira da Respiração da Névoa. Ele é uma pessoa avoada, dificilmente prestando atenção no que acontece ao seu redor. Isso também se reflete em seu modo irreverente de ver a vida, mas muda completamente para um humor sério quando alguém desonra seu mestre. Descendente de um Kizuki, sua respiração única foca em usar velocidade.',
  },
  {
    id: 15,
    name: 'Sanemi Shinazugawa',
    skills: ['Respiração do Vento'],
    image: 'https://kanto.legiaodosherois.com.br/w750-q90-k1/wp-content/uploads/2021/06/legiao_ACoEw7_DlX1F.jpg.jpeg',
    description: 'Sanemi Shinazugawa é o Hashira da Respiração do Vento. Mas diferente do elemento que é suave e silencioso, ele é violento, barulhento e impulsivo. Seu corpo coberto por cicatrizes é uma prova de seu pavio curto, uma vez que muitas delas foram feitas por ele mesmo.',
  },
]

export default charactersDemonSlayer;
